---
- name: Create temporary directory for inventory
  file:
    path: "{{ ansible_user_dir }}/tmp"
    state: directory
    mode: '0755'

- name: Copy inventory from executor to remote node
  copy:
    src: "{{ zuul.executor.inventory_file }}"
    dest: "{{ ansible_user_dir }}/tmp/inventory.yaml"
    mode: '0644'

- name: Verify inventory file was copied
  stat:
    path: "{{ ansible_user_dir }}/tmp/inventory.yaml"
  register: inventory_file

- name: Fail if inventory copy failed
  fail:
    msg: "Could not copy Zuul inventory file from executor"
  when: not inventory_file.stat.exists

- name: Set inventory path
  set_fact:
    zuul_inventory_path: "{{ ansible_user_dir }}/tmp/inventory.yaml"

- name: Create context extraction prompt with @file reference
  set_fact:
    context_prompt: >-
      Read and analyze the Zuul inventory file at @{{ zuul_inventory_path }}.
      Extract execution context including workspace locations, change information, and output paths.
      Generate a structured context summary following the zuul-context-extractor agent instructions.
      Write the output to {{ review_output_dir }}/zuul-context.md

- name: Execute context extraction
  include_tasks: tasks/run-opencode-command.yaml
  vars:
    agent_name: "zuul-context-extractor"
    model_name: "{{ context_model }}"
    agent_prompt: "{{ context_prompt }}"
    output_file: "{{ review_output_dir }}/zuul-context.md"
    command_name: "context extraction"
